### ISSUE TITLE
Add validate() method to class Timesheet

### ISSUE THREAD

**Issue by gma1083** [gma1083/hurricane#1]
**Description**:
On the timesheet class, write a non-static method to verify each property on a newly created instance of the timesheet class is of the proper type defined in the constructor. Throw a new and unique error for any property that does not contain a proper value. Errors should read '[property] is not valid'. Create unit test for the validate() method. 

**Acceptance Criteria**:
 If validate() method is called on an instance of Timesheet:
- if _id property is not a valid MongoDB objectID throw error described above
- if date property is not a valid date object throw error described above
- if employeeID property is not a valid MongoDB objectID throw error described above
- if jobID property is not a valid MongoDB objectID throw error described above
- if jobNumber, estCrewSize, estCrewHours, tmCrewSize, tmCrewHours, and yardsHauled are not each of type number throw an individual error for any as described above
- if lunchTaken, jobFinished, offHauled properties are not of type bool throw an individual error for any as described above
- if notes property is not of type string throw error as described above.

**Comment by cucucachu** [comment]
Branch reviewed and ready to merge to master. 

Merge the branch, add a comment here which explains your code changes, and then close this issue.
